name: Build on Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, updated]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: node

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install`

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build`
