name: Build on Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize, updated]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node
        uses: actions/setup-node@v3
        with:
          node-version: node

      - name: Install
        run: yarn install

      - name: Build Site
        run: yarn build
